name: Bump Version
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  bump-version:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      new_tag_name: ${{ steps.get_new_tag.outputs.new_tag_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get all history and tags
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Get git-chglog executable
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v0.15.0/git-chglog_0.15.0_linux_amd64.tar.gz
          tar --extract --file git-chglog_0.15.0_linux_amd64.tar.gz git-chglog
      - name: Install commitizen
        run: pip install commitizen
      - name: Get current tag
        run: |
          CUR_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "cur_tag=$CUR_TAG" >> $GITHUB_ENV
      - name: Commitizen bump # Bump version strings and add a new tag; commit
        run: cz bump
      - name: Get new tag
        id: get_new_tag
        run: |
          NEW_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          echo "::set-output name=new_tag_name::$NEW_TAG"
      - name: Generate CHANGELOG
        run: |
          ./git-chglog --output CHANGELOG.md
          git add CHANGELOG.md
          git tag -d ${{ env.new_tag }}
          git commit --amend --no-edit
          git tag ${{ env.new_tag }}
      - name: Push changes
        run: git push && git push origin ${{ env.new_tag }}
      - name: Generate incremental CHANGELOG for GitHub release body
        run: |
          ./git-chglog --template .chglog/RELEASE.tpl.md --output CHANGELOG_increment.md ${{ env.new_tag }}
          cat CHANGELOG_increment.md
      - uses: actions/upload-artifact@v2
        with:
          name: CHANGELOG_increment
          path: CHANGELOG_increment.md
  release-github-PyPI:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }} # otherwise we get the ref when the workflow started (missing above commit)
      - name: Build (for PyPI)
        run: mkdir release-artifacts
      - uses: actions/download-artifact@v2
        id: download_executables
        with:
          path: release-artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-artifacts/CHANGELOG_increment/CHANGELOG_increment.md
          tag_name: ${{ needs.bump-version.outputs.new_tag_name }}
          files: release-artifacts/git_branching_test-*/*
          release: ${{ github.ref == 'refs/heads/master' }}
